# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_c_approver',
            new_name='is_oc_approver',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_c_validator',
            new_name='is_oc_validator',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_vc_approver',
            new_name='is_ovc_approver',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_vc_validator',
            new_name='is_ovc_validator',
        ),
    ]
