# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160712_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('1', 'College of Arts and Social Sciences'), ('2', 'College of Business Administration and Accountancy'), ('3', 'College of Education'), ('4', 'College of Engineering'), ('5', 'College of Science and Mathematics'), ('6', 'School of Engineering Technology'), ('7', 'School of Computer Studies')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('1', 'Department of IT'), ('2', 'Department of Computer Science'), ('3', 'ECET Department')], default='1', max_length=1, null=True),
        ),
    ]
