# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'Submitted'), ('2', 'VC Received'), ('3', 'VC Approved'), ('4', 'VC Drafted'), ('5', 'C Received'), ('6', 'C Approved'), ('7', 'C Drafted')], default='1', max_length=2, null=True)),
                ('is_received', models.BooleanField(default=False, verbose_name='Document is Received')),
                ('requirement1', models.CharField(blank=True, choices=[('1', 'Request Form'), ('2', 'Document Stamp'), ('3', 'Requestor Name')], default='1', max_length=1, null=True)),
                ('requirement2', models.CharField(blank=True, choices=[('1', 'Request Form'), ('2', 'Document Stamp'), ('3', 'Requestor Name')], default='1', max_length=1, null=True)),
                ('date_received', models.DateField()),
                ('date_submitted', models.DateField()),
                ('date_checked', models.DateField()),
                ('date_requested', models.DateField()),
            ],
        ),
    ]
