# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='is_received',
        ),
        migrations.AddField(
            model_name='doc',
            name='date_oc_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='date_oc_validated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='date_ovc_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='date_ovc_validated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_oc_received',
            field=models.BooleanField(default=False, verbose_name='Document is Received at Chancellor Office'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_oc_validated',
            field=models.BooleanField(default=False, verbose_name='Document is Validated at Chancellor Office'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_ovc_approved',
            field=models.BooleanField(default=False, verbose_name='Document is Received at VC Office'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_ovc_received',
            field=models.BooleanField(default=False, verbose_name='Document is Received at VC Office'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_ovc_so_drafted',
            field=models.BooleanField(default=False, verbose_name='Document is Validated at VC Office'),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_ovc_validated',
            field=models.BooleanField(default=False, verbose_name='Document is Validated at VC Office'),
        ),
        migrations.AddField(
            model_name='doc',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
