# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts_app', '0003_auto_20160712_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('1', 'Travel Order'), ('2', 'Incentive Request'), ('3', 'Paper Presentation')], default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='person_incharge',
            field=models.CharField(blank=True, max_length=50, verbose_name='Person In-charge'),
        ),
    ]
