# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts_app', '0004_auto_20160712_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date_ovc_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='date_ovc_so_drafted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
