# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts_app', '0005_auto_20160712_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offices', models.CharField(blank=True, choices=[('1', 'OVCRE'), ('2', 'OVCAA'), ('3', 'OVCAF'), ('4', 'OVCPD')], default='1', max_length=1, null=True)),
            ],
        ),
    ]
